# This is a ci file for running a test script
image: ubuntu:focal

stages:
  - setup
  - build
  - cleanup

setup_job:
  tags:
    - docker
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - which python3
  stage: setup

build_job:
  tags:
    - docker
  dependencies:
    - setup_job
  script:
    - which python3
    - /usr/bin/python3 surlybot.py -b beer -n 5
  stage: build

cleanup_job:
  tags:
    - docker
  dependencies:
    - build_job
  script:
    - echo "all clean"
  stage: cleanup
