# This is a ci file for running a test script
image: ubuntu:focal

variables:
  CLUSTER: kubernetes
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Cache Python Packages
cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/pip

stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - pip install --upgrade pip
  - python3 -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build_job:
  tags:
    - $CLUSTER
  script:
    - /usr/bin/python3 surlybot.py -b beer -n 5 2>&1 | tee -a artifact.txt
  artifacts:
    paths:
      - artifact.txt
    expire_in: 1 week
  stage: build

#
# EOF
#
