# This is a ci file for running a test script
image: ubuntu:focal

stages:
  - build
  - cleanup

build_job:
  tags:
    - docker
  script:
    - python3 surlybot.py -b beer -n 5
  stage: build

cleanup_job:
  tags:
    - docker
  dependencies:
    - build_job
  script:
    - echo "all clean"
  stage: cleanup
