# This is a ci file for running a test script

stages:
  - build
  - cleanup

build_job:
  script:
    - python3 surlybot.py -b beer -n 5
  stage: build

cleanup_job:
  dependencies:
    - build_job
  script:
    - echo "all clean"
  stage: cleanup
