# This is a ci file for running a test script
image: ubuntu:focal

stages:
  - build

build_job:
  tags:
    - $CLUSTER
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - /usr/bin/python3 surlybot.py -b beer -n 5 2>&1 | tee -a artifact.txt
  artifacts:
    paths:
      - artifact.txt
    expire_in: 1 week
  stage: build
