# This is a ci file for running a test script
name: surlybot
on:
  push:
    tags: docker
    branches:
      - master
      - self-hosted-runner

jobs:
  build_job:
    runs-on: self-hosted
    #runs-on: ubuntu-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Update OS
        run: apt-get update -qy
      - name: Install Python3
        run: apt-get install -y python3 python3-pip
      - name: Another Round for the House
        run: /usr/bin/python3 surlybot.py -b beer -n 5 2>&1 | tee -a artifact.txt
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Lyrics
          path: artifact.txt
          retention-days: 7
